# Generated by Django 5.2.12 on 2026-03-24 09:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('quest_type', models.CharField(choices=[('calorie_goal', 'Hit Calorie Goal'), ('log_weight', 'Log Your Weight'), ('big_meal', 'Eat a Big Meal'), ('early_meal', 'Log Before Noon')], max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('target_value', models.PositiveIntegerField(default=1)),
                ('current_value', models.PositiveIntegerField(default=0)),
                ('xp_reward', models.PositiveIntegerField(default=50)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'completed'],
                'unique_together': {('user', 'date', 'quest_type')},
            },
        ),
    ]
