# Generated by Django 5.2.12 on 2026-03-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterprofile',
            name='last_log_date',
            field=models.DateField(blank=True, help_text='Last date the user logged anything', null=True),
        ),
        migrations.AddField(
            model_name='characterprofile',
            name='streak',
            field=models.PositiveIntegerField(default=0, help_text='Consecutive days with at least one log'),
        ),
    ]
